### ISSUE TITLE
On load: "The frame index requested is beyond the end of the file."

### ISSUE THREAD

**Issue by dmyersturnbull** [alperezescudero/idTracker#10]
With a checkout of the beta branch and MATLAB 2016a, I get an error after the GUI is drawn when running with two arguments.

```
>> idTracker ../.. out.mp4

1,
Guarning!
Starting parallel pool (parpool) using the 'local' profile ... connected to 2 workers.
Error using VideoReader/read (line 160)
The frame index requested is beyond the end of the file.

Error in panel_identitracking (line 175)
frame=read(datosegm.obj{1},1);


Error in idTracker (line 285)
            [datosegm,h_panel]=panel_identitracking(datosegm);
```

The line numbers are different for `idTracker.m` because I commented out the try and catch to see the error message (otherwise it fails in the catch block due to `datosegm` being undefined).

Here's line 285 of `idTracker.m`:

``` matlab
        if ~isfield(datosegm,'muestrapanel') || datosegm.muestrapanel
            [datosegm,h_panel]=panel_identitracking(datosegm);  # <------------------- line 285
        end
```

And here's line 175 of `panel_identitracking.m` for reference:

``` matlab
datos.videoabierto=1;
frame=read(datosegm.obj{1},1); # <---------- line 175
if size(frame,3)==3
    frame=rgb2gray(frame);
end
```

**Comment by dmyersturnbull** [comment]
Also, my intention was to run idTracker without showing the GUI.

**Comment by ahof1704** [comment]
Hi Douglas,

Let's try to figure out what is your problem. 

I just tried to reproduce the error that you got, but it did't happen to me here... 

It could have been caused for some reasons, for example:
1) "datosegm.obj" was not created
In this case, it could have happened if the methods we used for video loading was not compatible to any version of Matlab we predicated. This would be really weird, because we are using the only two methods that Matlab presented so far for video reading. Maybe the path to your video file is not right when we construct the path string. 

2)  "datosegm" was not created or it was deleted for some reason.
Even more weird than my previous guess. 

So let's go step-by-step:
1) When you get to line 175 in "panel_identitracking", do you have a datosegm in your workspace? What about datosegm.obj?

2) Also, when you get to this line, copy this command and paste at your Command window at matlab and let us know what you got:

[datosegm.directorio_videos datosegm.raizarchivo_videos '.' datosegm.extension]

Thank you!
Antonio.

**Comment by dmyersturnbull** [comment]
1. I have `datosegm` and `datosegm.obj` in my workspace, and `datosegm.obj` seems to have the video with the correct path and number of frames (`Width`).
2. Stopped on line 175:

```
K>> [datosegm.directorio_videos datosegm.raizarchivo_videos '.' datosegm.extension]

ans =

../../out.mp4
```

Which is the correct path of the video.

**Comment by dmyersturnbull** [comment]
When running on the example video, I instead get:

```

>> idTracker ../.. 5Zebrafish_nocover_22min.avi
1,Error using VideoReader/init (line 619)
Failed to initialize internal resources.

Error in VideoReader (line 172)
            obj.init(fileName);

Error in directorio2datosegm (line 84)
            datosegm.obj{c_archivos}=VideoReader([directorio raizarchivo '.' datosegm.extension]);


Error in idTracker (line 169)
        datosegm=directorio2datosegm(directorio,raizarchivos,directorio_destino,extension);
```

**Comment by ahof1704** [comment]
Hi,

It works fine for me here... Try execute again using an expression like this:
idTracker('path_to_video','video_name')

Example:

> > idTracker('E:\idTracker_debug', '2014_04_03_18-55-02.985-Segment 7.avi')

Keep us posted! 

Thanks!
Antonio.

**Comment by dmyersturnbull** [comment]
Thanks for the replies! Same thing though.

```
>> idTracker('../..', '5Zebrafish_nocover_22min.avi')
1,Error using VideoReader/init (line 619)
Failed to initialize internal resources.

Error in VideoReader (line 172)
            obj.init(fileName);

Error in directorio2datosegm (line 84)
            datosegm.obj{c_archivos}=VideoReader([directorio raizarchivo '.' datosegm.extension]);


Error in idTracker (line 169)
        datosegm=directorio2datosegm(directorio,raizarchivos,directorio_destino,extension);
```

As an aside, using a nonexistent file leads to a different but unhelpful error message:

```
>> idTracker('../..', 'asdhaeyhaefhadfha')
Index exceeds matrix dimensions.

Error in directorio2datosegm (line 54)
datosegm.extension=esta(1).name(end-2:end);


Error in idTracker (line 169)
        datosegm=directorio2datosegm(directorio,raizarchivos,directorio_destino,extension);

```

**Comment by ahof1704** [comment]
Hi,

Let's start with your second test:

> > idTracker('../..', 'asdhaeyhaefhadfha')

In your second example, it looks a lot like the path is wrong. If you check
the content of "esta", you are going to see that this variable is probably
empty because it failed at this line previously:
*esta=dir([directorio raizarchivo num2str(c_archivos) '.' extension]);
[Line 43 - directorio2datosegm] *

because the command "dir" returned "not found" for this file you are
looking for.

Now let's talk about the first test:

> > idTracker('../..', '5Zebrafish_nocover_22min.avi')

I suppose you are running it in a Mac, right? If this is the case, you may
want to take a look on some forums about how to deal with codecs for your
case.
Some links that might be useful:
1) Suggests converting your video MP4 file to QuickTime format
http://stackoverflow.com/questions/15662486/matlab-videoreader-frames-arent-decoded-accurately

2) Similar to the last one:
http://stackoverflow.com/questions/22773403/cant-read-an-avi-file-to-matlab-using-videoread

Hope it helps!

Antonio.

On Tue, Jun 14, 2016 at 4:42 PM, Douglas Myers-Turnbull <
notifications@github.com> wrote:

> Same thing.
> 
> > > idTracker('../..', '5Zebrafish_nocover_22min.avi')
> > > 1,Error using VideoReader/init (line 619)
> > > Failed to initialize internal resources.
> 
> Error in VideoReader (line 172)
>             obj.init(fileName);
> 
> Error in directorio2datosegm (line 84)
>             datosegm.obj{c_archivos}=VideoReader([directorio raizarchivo '.' datosegm.extension]);
> 
> Error in idTracker (line 169)
>         datosegm=directorio2datosegm(directorio,raizarchivos,directorio_destino,extension);
> 
> As an aside, using a nonexistent file leads to a different but unhelpful
> error message:
> 
> > > idTracker('../..', 'asdhaeyhaefhadfha')
> > > Index exceeds matrix dimensions.
> 
> Error in directorio2datosegm (line 54)
> datosegm.extension=esta(1).name(end-2:end);
> 
> Error in idTracker (line 169)
>         datosegm=directorio2datosegm(directorio,raizarchivos,directorio_destino,extension);
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/idTracker/idTracker/issues/10#issuecomment-226009795,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHukxPjc3voNuVvwXN25e15120HmxJhWks5qLxI2gaJpZM4Iz5o-
> .

## 

Antonio Henrique de Oliveira Fonseca
antonio.fonseca@yale.edu
Automation, Instrumentation and Robotics Engineering - UFABC / Laurentian
University.
Post-Graduate Associate in Comparative Medicine - Yale School of Medicine

**Comment by dmyersturnbull** [comment]
> In your second example, it looks a lot like the path is wrong.

Yes, my point was only that the error message could be more helpful for when a video doesn't exist. That, and the original error wasn't caused by the path being wrong (because the errors are different).

You're right that missing codecs were the issue for `5Zebrafish_nocover_22min.avi`! I'm glad to understand that issue. However, the original error occurred with an H264-encoded video in a MPEG-4 container, which MATLAB says it supports on Mac: https://www.mathworks.com/help/matlab/import_export/supported-video-file-formats.html
Indeed, it can load that video:

```
>> VideoReader('../../out.mp4')

ans = 

  VideoReader with properties:

   General Properties:
            Name: 'out.mp4'
            Path: 'lab'
        Duration: 75
     CurrentTime: 0
             Tag: ''
        UserData: []

   Video Properties:
           Width: 1180
          Height: 796
       FrameRate: 10
    BitsPerPixel: 24
     VideoFormat: 'RGB24'
```

Whereas it couldn't for `5Zebrafish_nocover_22min.avi`. But I still get the error `The frame index requested is beyond the end of the file.` with my H264 `out.mp4`.

**Comment by dmyersturnbull** [comment]
Thanks for the help so far! I found the problem, and it's not a bug in idTracker: https://apple.stackexchange.com/questions/166553/why-wont-video-from-ffmpeg-show-in-quicktime-imovie-or-quick-preview

However, I'd like to run idTracker without starting up the GUI, which calling `idTracker('../..', 'test.mp4')` does. How can I do this?

I can open a new issue for this if that's preferred.

**Comment by dmyersturnbull** [comment]
I also got an error when segmenting:

```

>> idTracker('../..', 'test.mp4')
1,
Guarning!
Starting parallel pool (parpool) using the 'local' profile ... connected to 2 workers.
Video detected as b/w
Parece que se pueden leer todos los frames de golpe
1,

200,300,500,600,700,800,900,

Trozo 1:
.
.
.
Trozo 1085:
Trozo 1086:1,

200,300,500,600,700,800,900,
Intervalos buenos
Referencias
Reference to non-existent field 'ref2trozos'.

Error in datosegm2referencias (line 470)
    trozos_act=listamapas.ref2trozos{ind}(c_peces,~listamapas.solapanconcogidos{ind}(c_peces,:));


Error in idTracker (line 707)
                                [referencias,listamapas]=datosegm2referencias(datosegm,intervalosbuenos,trozos,datosegm.nframes_refs,h_panel);
```

And here's the context for line 707 for me:

``` matlab
[referencias,listamapas]=datosegm2referencias(datosegm,intervalosbuenos,trozos,datosegm.nframes_refs,h_panel);   # <------------------------ line 707
datosegm.tiempos.referencias(2)=now;
variable=datosegm;
save([datosegm.directorio 'datosegm.mat'],'variable')
```

**Comment by ahof1704** [comment]
From what I have seen on the code so far (I've been working on it for only one month now), I think run idTracker without GUI is not an option. 
There is a variable that should control it:
_datosegm.muestrapanel_

And by setting _datosegm.muestrapanel = 0_ we should be able to suppress the GUI, but for now there are other tasks that depend on the GUI to be done (not exactly the GUI, but the function that calls the GUI) and suppressing it causes idTracker to crash for other reasons. 

Maybe someone else knows a workaround for it.

Otherwise, we can consider it to be done in the future I guess. 

Thanks!
Antonio.

**Comment by dmyersturnbull** [comment]
Thanks!

We can live with the GUI being displayed. Is there a way to call the idTracker process (invoked by clicking "Start") programmatically from the MATLAB command-line, even if the GUI is displayed? In other words, the GUI is displayed, but the user doesn't need to click on anything. It seems like I could run `datosegm.saltatodo = true;` (or similar), but I can't enter anything at the MATLAB terminal once the GUI is displayed.

The error `Reference to non-existent field 'ref2trozos'` is a current showstopper for us using idTracker. It looks like `ref2trozos` is declared only under certain conditions nested in a couple of if statements.

**Comment by alperezescudero** [comment]
Hi!

About using idTracker programmatically, it is definitely possible, but this option is not very well documented. You have some information here:

http://www.idtracker.es/user-forum?place=msg%2Fidtracker-users%2F-vOE7hvtZtY%2FNqd0Hi4cAwAJ

**Comment by dmyersturnbull** [comment]
Okay, thanks! I'll give that a shot.
