### ISSUE TITLE
Maximum size parameter

### ISSUE THREAD

**Issue by dmyersturnbull** [alperezescudero/idTracker#13]
There's a parameter for minimum size but not for maximum size. In our videos, idTracker tends to merge the images of zebrafish that are near each other. Perhaps restricting individuals to a maximum size would prevent this?

**Comment by alperezescudero** [comment]
Using a maximum size to prevent merging of two fish is tricky, because the size of two merged fish is often not so different from the size of a single individual (depending on posture, amount of overlapping, etc.). Also, idTracker will anyway realize eventually that two overlapping fish are not an individual, and take that into account. Finally, those events where two fish are touching only in a few pixels will be resolved in the "resegmentation" step (you cannot see this from the interface, but in the final result the two individuals will appear separated). 

This said, idTracker does have a maximum size threshold, which is set at a very high size to prevent memory overflow. You cannot edit it from the interface; it is the field umbral_npixelsmax in the variable datosegm.

**Comment by dmyersturnbull** [comment]
Great, thanks for the reply. I see it in mentioned at [description of idTracker's main variables](https://github.com/idTracker/idTracker/wiki/Description-of-idTracker's-main-variables).
